# Generated by Django 3.1.1 on 2020-09-21 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
